// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeyk-CdQrrYYqqR8gOMoLAGvMi0aoOH9s',
    appId: '1:308402552624:web:2a47880f22426cd5ec12f5',
    messagingSenderId: '308402552624',
    projectId: 'swp490-gm',
    authDomain: 'swp490-gm.firebaseapp.com',
    storageBucket: 'swp490-gm.appspot.com',
    measurementId: 'G-VS22LNV1WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2QPfLfxhvvNzajLtclNmlCHp3wWz-Dhc',
    appId: '1:308402552624:android:438cb33b189e085eec12f5',
    messagingSenderId: '308402552624',
    projectId: 'swp490-gm',
    storageBucket: 'swp490-gm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oQ8FEl0bc1oCvPsF5TuCaKQ0PC1Y0JY',
    appId: '1:308402552624:ios:2dd0537580147c3bec12f5',
    messagingSenderId: '308402552624',
    projectId: 'swp490-gm',
    storageBucket: 'swp490-gm.appspot.com',
    iosClientId: '308402552624-p8ucgqrur1q1ll1i2007v9tm8a3kgplt.apps.googleusercontent.com',
    iosBundleId: 'com.example.egtspt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7oQ8FEl0bc1oCvPsF5TuCaKQ0PC1Y0JY',
    appId: '1:308402552624:ios:f9fb33edb0529fcbec12f5',
    messagingSenderId: '308402552624',
    projectId: 'swp490-gm',
    storageBucket: 'swp490-gm.appspot.com',
    iosClientId: '308402552624-jvrfq15smtsmckqudps0dj59f1161ph9.apps.googleusercontent.com',
    iosBundleId: 'com.example.egtspt.RunnerTests',
  );
}
